import math

APP_NAME = "ZarCalc"
APP_VERSION = "1.8.0"

COLORS = [
    "#e74c3c", "#3498db", "#2ecc71", "#f39c12", "#9b59b6",
    "#1abc9c", "#e67e22", "#c0392b", "#e91e63", "#00bcd4",
]

PRESETS = {
    "sin(x)":           ("sin(x)",                                      None,          None),
    "cos(x)":           ("cos(x)",                                      None,          None),
    "tan(x)":           ("tan(x)",                                      None,          None),
    "x^2":              ("x**2",                                        None,          None),
    "x^3":              ("x**3",                                        None,          None),
    "x^4 - x^2":        ("x**4 - x**2",                                None,          None),
    "sqrt(x)":          ("sqrt(x)",                                     None,          None),
    "cbrt(x)":          ("sign(x)*abs(x)**(1/3)",                      None,          None),
    "exp(x)":           ("exp(x)",                                      None,          None),
    "ln(x)":            ("log(x)",                                      None,          None),
    "log10(x)":         ("log10(x)",                                    None,          None),
    "abs(x)":           ("abs(x)",                                      None,          None),
    "1/x":              ("1/x",                                         None,          None),
    "floor(x)":         ("floor(x)",                                    None,          None),
    "frac(x)":          ("frac(x)",                                     None,          None),
    "sin(x)/x":         ("sin(x)/x if x!=0 else 1",                    None,          None),
    "Gauss":            ("exp(-x**2/2)",                                None,          None),
    "Sigmoid":          ("sigmoid(x)",                                  None,          None),
    "Tanh":             ("tanh(x)",                                     None,          None),
    "Softsign":         ("x/(1+abs(x))",                               None,          None),
    "Sawtooth":         ("sawtooth(x)",                                 None,          None),
    "Square":           ("square(x)",                                   None,          None),
    "Triangle":         ("tri(frac(x/pi+0.5)-0.5)*2-1",               None,          None),
    "Sinc":             ("sinc(x)",                                     None,          None),
    "Sinc^2":           ("sinc(x)**2",                                  None,          None),
    "Fresnel-like":     ("sin(x**2)",                                   None,          None),
    "Chirp":            ("sin(x**2/(2*pi))",                            None,          None),
    "Damped osc":       ("exp(-0.3*abs(x))*cos(4*x)",                  None,          None),
    "Beating":          ("sin(5*x)+sin(5.3*x)",                        None,          None),
    "AM+FM":            ("(1+0.5*sin(0.5*x))*sin(8*x)",               None,          None),
    "Phase mod":        ("sin(x+sin(3*x))",                             None,          None),
    "Harmonic comb":    ("sin(x)+sin(2*x)/2+sin(3*x)/3+sin(4*x)/4+sin(5*x)/5", None, None),
    "Resonance":        ("x/((1-x**2)**2+(0.1*x)**2)**0.5",           None,          None),
    "Runge":            ("1/(1+25*x**2)",                               None,          None),
    "Erf-ish":          ("x*exp(-x**2/4)",                             None,          None),
    "Abs sin frac":     ("abs(sin(pi*x))*frac(x)",                     None,          None),
    "Devil staircase":  ("floor(sin(pi*x)*4)/4",                       None,          None),
    "Cantor-ish":       ("sin(pi*x)*sin(pi*x*3)*sin(pi*x*9)",         None,          None),
    "Weierstrass":      ("sin(x)+sin(3*x)/3+sin(9*x)/9+sin(27*x)/27+sin(81*x)/81", None, None),
    "Square+sin":       ("square(x)*sin(x)",                           None,          None),
    "Saw harmonic":     ("sawtooth(x)+0.3*sin(5*x)",                   None,          None),
    "Sigmoid chain":    ("sigmoid(x)*sigmoid(-x+5)*sigmoid(x+5)",      None,          None),
    "Tanh sigmoid":     ("tanh(3*x)-tanh(x-3)+tanh(x+3)",             None,          None),
    "Erf approx":       ("tanh(sqrt(pi)*x/2)",                         None,          None),
    "Logistic S":       ("1/(1+exp(-3*(x-2)))-1/(1+exp(-3*(x+2)))",   None,          None),
    "Clamp wave":       ("clamp(sin(x)*2,-1,1)",                       None,          None),
    "Rectified sin":    ("abs(sin(x))",                                 None,          None),
    "Saw+square":       ("sawtooth(x)*0.5+square(x)*0.5",             None,          None),
    "Gaussian comb":    ("gaussian(x-2)+gaussian(x)+gaussian(x+2)",    None,          None),
    "Logistic map":     ("3.9*x*(1-x)",                                 None,          None),
    "Tent map":         ("2*x if x<0.5 else 2*(1-x)",                  None,          None),
    "Chaos logistic":   ("3.7*x*(1-x)",                                None,          None),
    "Double-well":      ("x**4-2*x**2",                                None,          None),
    "Mexican hat":      ("(1-x**2)*exp(-x**2/2)",                      None,          None),
    "Bump":             ("exp(-1/(1-x**2)) if abs(x)<1 else 0",        None,          None),
    "Witch of Agnesi":  ("8/(x**2+4)",                                  None,          None),
    "Sech":             ("1/cosh(x)",                                   None,          None),
    "Step":             ("step(x)",                                     None,          None),
    "Rect":             ("rect(x)",                                     None,          None),
    "Lissajous":        ("sin(3*t)",                                    "parametric",  "cos(2*t)"),
    "Circle":           ("cos(t)",                                      "parametric",  "sin(t)"),
    "Ellipse":          ("2*cos(t)",                                    "parametric",  "sin(t)"),
    "Spiral":           ("t*cos(t)",                                    "parametric",  "t*sin(t)"),
    "Fermat spiral":    ("t**0.5*cos(t)",                               "parametric",  "t**0.5*sin(t)"),
    "Heart":            ("16*sin(t)**3",                                "parametric",  "13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t)"),
    "Butterfly":        ("sin(t)*(exp(cos(t))-2*cos(4*t))",            "parametric",  "cos(t)*(exp(cos(t))-2*cos(4*t))"),
    "Rose cos(3t)":     ("cos(3*t)*cos(t)",                            "parametric",  "cos(3*t)*sin(t)"),
    "Astroid":          ("cos(t)**3",                                   "parametric",  "sin(t)**3"),
    "Deltoid":          ("2*cos(t)+cos(2*t)",                          "parametric",  "2*sin(t)-sin(2*t)"),
    "Nephroid":         ("3*cos(t)-cos(3*t)",                          "parametric",  "3*sin(t)-sin(3*t)"),
    "Cardioid":         ("2*cos(t)*(1-cos(t))",                        "parametric",  "2*sin(t)*(1-cos(t))"),
    "Lemniscate":       ("cos(t)/(1+sin(t)**2)",                       "parametric",  "sin(t)*cos(t)/(1+sin(t)**2)"),
    "Hypotrochoid":     ("3*cos(t)+cos(3*t)*0.5",                      "parametric",  "3*sin(t)-sin(3*t)*0.5"),
    "Hypotrochoid 5/3": ("(5-3)*cos(t)+2*cos((5-3)/3*t)",             "parametric",  "(5-3)*sin(t)-2*sin((5-3)/3*t)"),
    "Epitrochoid":      ("(3+1)*cos(t)-1*cos((3+1)*t)",               "parametric",  "(3+1)*sin(t)-1*sin((3+1)*t)"),
    "Involute":         ("cos(t)+t*sin(t)",                             "parametric",  "sin(t)-t*cos(t)"),
    "Kampyle":          ("1/cos(t)**2",                                 "parametric",  "tan(t)/cos(t)**2"),
    "Talbot":           ("(1+0.9*sin(t)**2)*cos(t)",                   "parametric",  "(1-0.9*sin(t)**2)*sin(t)*1.5"),
    "Watt":             ("2*sin(t)+sin(2*t)",                          "parametric",  "2*cos(t)-cos(2*t)+1"),
    "Limacon":          ("(1+0.7*cos(t))*cos(t)",                      "parametric",  "(1+0.7*cos(t))*sin(t)"),
    "Folium":           ("3*t/(1+t**3)",                                "parametric",  "3*t**2/(1+t**3)"),
    "Tschirnhaus":      ("t**2",                                        "parametric",  "t**3-t"),
    "Knot":             ("cos(t)+2*cos(2*t)",                          "parametric",  "sin(t)-2*sin(2*t)"),
    "Double egg":       ("cos(t)*(1+0.5*cos(2*t))",                    "parametric",  "sin(t)*(1+0.5*cos(2*t))"),
    "Rhodonea 5":       ("cos(5*t)*cos(t)",                            "parametric",  "cos(5*t)*sin(t)"),
    "Rhodonea 7/2":     ("cos(7*t/2)*cos(t)",                          "parametric",  "cos(7*t/2)*sin(t)"),
    "Lissajous 5:4":    ("sin(5*t+0.3)",                               "parametric",  "sin(4*t)"),
    "Lissajous 7:6":    ("sin(7*t+pi/4)",                              "parametric",  "sin(6*t)"),
    "Superellipse":     ("sign(cos(t))*abs(cos(t))**0.6",              "parametric",  "sign(sin(t))*abs(sin(t))**0.6"),
    "Gear 8":           ("(1+0.15*cos(8*t))*cos(t)",                   "parametric",  "(1+0.15*cos(8*t))*sin(t)"),
    "Klein-ish":        ("sin(t/2)*sin(t)",                            "parametric",  "sin(t/2)*cos(t)"),
    "Spirograph 7/3":   ("4*cos(t)+cos(4*t/3*7)",                      "parametric",  "4*sin(t)-sin(4*t/3*7)"),
    "Butterfly2":       ("sin(t)*cos(t)**2",                            "parametric",  "sin(t)**2*cos(t)"),
    "Maclaurin":        ("cos(t)**3",                                   "parametric",  "sin(t)**3+0.5*sin(3*t)"),
    "Tricuspoid":       ("2*cos(t)+cos(2*t)",                          "parametric",  "2*sin(t)-sin(2*t)"),
    "Nephroid2":        ("cos(t/3)**3",                                 "parametric",  "sin(t/3)**3"),
    "Torus knot 3/5":   ("cos(3*t)*(2+cos(5*t))",                     "parametric",  "sin(3*t)*(2+cos(5*t))"),
    "Torus knot 2/3":   ("cos(2*t)*(2+cos(3*t))",                     "parametric",  "sin(2*t)*(2+cos(3*t))"),
    "Epicycloid 5":     ("6*cos(t)-cos(6*t)",                          "parametric",  "6*sin(t)-sin(6*t)"),
    "Spring":           ("cos(t)*(2+cos(t*5))",                        "parametric",  "sin(t)*(2+cos(t*5))"),
    "Bifolium":         ("sin(t)**2*cos(t)",                            "parametric",  "sin(t)**3"),
    "Strophoid":        ("cos(2*t)/cos(t)",                             "parametric",  "sin(t)*cos(2*t)/cos(t)"),
}

SAFE_NS = {
    "sin": math.sin, "cos": math.cos, "tan": math.tan,
    "asin": math.asin, "acos": math.acos, "atan": math.atan, "atan2": math.atan2,
    "sinh": math.sinh, "cosh": math.cosh, "tanh": math.tanh,
    "sqrt": math.sqrt, "exp": math.exp, "log": math.log,
    "log2": math.log2, "log10": math.log10,
    "abs": abs, "floor": math.floor, "ceil": math.ceil,
    "round": round, "pi": math.pi, "e": math.e, "inf": math.inf,
    "sign":     lambda x: (1 if x > 0 else -1 if x < 0 else 0),
    "frac":     lambda x: x - math.floor(x),
    "clamp":    lambda x, a, b: max(a, min(b, x)),
    "mod":      math.fmod,
    "hypot":    math.hypot,
    "factorial": math.factorial,
    "degrees":  math.degrees,
    "radians":  math.radians,
    "sigmoid":  lambda x: 1 / (1 + math.exp(-x)),
    "step":     lambda x: 1.0 if x >= 0 else 0.0,
    "rect":     lambda x: 1.0 if abs(x) <= 0.5 else 0.0,
    "tri":      lambda x: max(0.0, 1.0 - abs(x)),
    "sawtooth": lambda x: 2 * (x / (2 * math.pi) - math.floor(0.5 + x / (2 * math.pi))),
    "square":   lambda x: 1.0 if math.sin(x) >= 0 else -1.0,
    "sinc":     lambda x: math.sin(math.pi * x) / (math.pi * x) if x != 0 else 1.0,
    "gaussian": lambda x: math.exp(-x * x / 2),
    "lerp":     lambda a, b, t: a + (b - a) * t,
    "sech":     lambda x: 1.0 / math.cosh(x),
    "__builtins__": {},
}

DEFAULT_XMIN    = -10.0
DEFAULT_XMAX    =  10.0
DEFAULT_YMIN    =  -8.0
DEFAULT_YMAX    =   8.0
DEFAULT_TMIN    = -2 * math.pi
DEFAULT_TMAX    =  2 * math.pi
DEFAULT_MINPTS  = 800
DEFAULT_MAXPTS  = 80000
DEFAULT_SAMPLES = 800
ANIM_INTERVAL_MS = 30
ANIM_STEP = 0.06
DERIV_H = 1e-5
INFINITE_MARGIN = 5.0